### ISSUE TITLE
4 pages added

### ISSUE THREAD

**Issue by hiewying** [hiewying/Tafe17S202#1]
hello, i've already added PERSONAL INFO , CONTACT DETAILS, APPOINTMENTS & SHOPPING LIST xaml pages into Views folder. And i also added those hamburgerButtonInfo (tabs on left side) into Shell.xaml

Personal Info - Hiew Ying
Contact Details - Eric
Appointments - Daphne
Shopping List - Edward 

 GOOD LUCK WITH DESIGN & CODING !!!!!

**Comment by daph1301** [comment]
Thanks Hiew Ying!
